# Generated by Django 2.2 on 2019-04-17 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoBarras', models.CharField(max_length=14)),
                ('precio', models.DecimalField(decimal_places=3, max_digits=7)),
                ('unidades', models.IntegerField(default=0)),
                ('iva', models.DecimalField(decimal_places=2, max_digits=2)),
                ('nombre', models.CharField(max_length=15)),
                ('categoria', models.CharField(max_length=15)),
            ],
        ),
    ]
