# Generated by Django 2.2 on 2019-04-18 02:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ventas', '0005_auto_20190418_0125'),
    ]

    operations = [
        migrations.CreateModel(
            name='reporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=datetime.datetime.now)),
                ('total', models.FloatField(default=0)),
                ('ventas', models.ManyToManyField(to='ventas.venta')),
            ],
        ),
    ]
