# Generated by Django 2.2 on 2019-04-18 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_auto_20190418_0125'),
        ('reportes', '0002_auto_20190418_0910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporte',
            name='productos',
        ),
        migrations.AddField(
            model_name='reporte',
            name='ventas',
            field=models.ManyToManyField(to='ventas.venta'),
        ),
    ]
