# Generated by Django 2.2 on 2019-04-18 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_auto_20190417_1050'),
        ('reportes', '0003_auto_20190418_0915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporte',
            name='ventas',
        ),
        migrations.AddField(
            model_name='reporte',
            name='productos',
            field=models.ManyToManyField(to='productos.producto'),
        ),
    ]
