# Generated by Django 2.2 on 2019-04-18 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ventas', '0005_auto_20190418_0125'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('venta', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='ventas.venta')),
            ],
        ),
    ]
