# Generated by Django 2.1.7 on 2019-05-21 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=50)),
                ('sale', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='venta.Sale')),
            ],
        ),
    ]
