# Generated by Django 2.1.7 on 2019-05-21 02:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('paymentType', models.CharField(default='efectivo', max_length=50)),
                ('products', models.CharField(max_length=150)),
                ('value', models.FloatField(default=0)),
            ],
        ),
    ]
