# Generated by Django 2.1.7 on 2019-05-21 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='bascula',
            field=models.FloatField(),
        ),
    ]
