# Generated by Django 2.2 on 2019-04-17 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ventas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idVenta', models.IntegerField(default=0)),
                ('idProducto', models.CharField(max_length=14)),
                ('cantidad', models.IntegerField(default=0)),
            ],
        ),
    ]
