# Generated by Django 2.2 on 2019-04-17 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_auto_20190417_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='valor',
            field=models.FloatField(),
        ),
    ]
